/**
 * URL patterns and cache names for the member service worker, shared by the
 * build config (`vite.config.ts`) and the post-build gate
 * (`scripts/check-service-worker.ts`) so the two can never drift.
 *
 * Every pattern is built from the deployed base path, which differs per
 * environment ('/' locally, '/CollectiveKhatma/' on GitHub Pages).
 */

/** Escape a literal path for embedding in a RegExp source. */
export function escapeRegExp(value: string): string {
  return value.replaceAll(/[$()*+.?[\\\]^{|}]/g, (character) => `\\${character}`);
}

/**
 * Matches the base path and nothing below it. Hash routing means the member app
 * only ever navigates to that one URL, so allowlisting it keeps the navigation
 * fallback off every other path — notably the hidden admin entry, which must
 * keep reaching the network.
 */
export function basePathOnly(base: string): RegExp {
  return new RegExp(`^${escapeRegExp(base)}$`);
}

/**
 * Runtime cache holding the mushaf: 604 page files plus `surahs.json` and
 * `index.json`, generated by `scripts/build-quran-data.ts` and committed under
 * `public/quran/`.
 *
 * The bytes behind a given URL never change, so the worker serves them
 * cache-first with no revalidation and a page downloads once per device, ever.
 * The version suffix is that guarantee's only escape hatch: bump it when
 * `npm run build:quran` rewrites the dataset, and delete the superseded cache
 * by hand — workbox's `cleanupOutdatedCaches` prunes precaches, not this one.
 */
export const QURAN_CACHE_NAME = 'quran-mushaf-v1';

/**
 * Matches every mushaf JSON request under the base path. Left unanchored on
 * purpose: workbox matches a RegExp anywhere within a same-origin request URL,
 * and anchoring would fail against the leading origin.
 */
export function quranDatasetRoute(base: string): RegExp {
  return new RegExp(`${escapeRegExp(base)}quran/.+\\.json$`);
}
