import type { QuranIndex, QuranPage, Surah } from './types';

/**
 * Typed access to the bundled Quran dataset. The raw JSON lives in
 * `public/quran/` (generated by `scripts/build-quran-data.ts`) and is served as
 * static assets, so it stays out of the JS bundle and is fetched — and cached —
 * only as needed.
 *
 * `import.meta.env.BASE_URL` is Vite's base path ('/' in dev, '/<repo>/' on
 * GitHub Pages), so these URLs resolve correctly in every environment.
 */
const base = import.meta.env.BASE_URL;

const pageCache = new Map<number, Promise<QuranPage>>();
let surahsCache: Promise<Surah[]> | undefined;
let indexCache: Promise<QuranIndex> | undefined;

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to load ${url}: ${res.status}`);
  return (await res.json()) as T;
}

/** Load a single mushaf page (1..604). Cached after first load. */
export function getPage(page: number): Promise<QuranPage> {
  let cached = pageCache.get(page);
  if (!cached) {
    const file = `${base}quran/pages/${String(page).padStart(3, '0')}.json`;
    cached = fetchJson<QuranPage>(file);
    pageCache.set(page, cached);
  }
  return cached;
}

/** Load surah metadata (headings, chapter page ranges for assignment). Cached. */
export function getSurahs(): Promise<Surah[]> {
  return (surahsCache ??= fetchJson<Surah[]>(`${base}quran/surahs.json`));
}

/** Load the navigation / assignment-resolution index. Cached. */
export function getQuranIndex(): Promise<QuranIndex> {
  return (indexCache ??= fetchJson<QuranIndex>(`${base}quran/index.json`));
}
