/**
 * Quran dataset shapes — the Madinah (King Fahd / KFGQPC) mushaf, Hafs Uthmani.
 *
 * The raw JSON lives under `public/quran/` (generated by
 * `scripts/build-quran-data.ts`, committed to the repo) and is fetched at
 * runtime by `loader.ts`. Pages are the atomic unit used for assignment; surah
 * metadata lets the admin also assign by whole chapter.
 */

/** A single ayah as it appears in the Madinah mushaf. */
export interface Ayah {
  /** Surah number, 1..114. */
  surah: number;
  /** Ayah number within the surah. */
  ayah: number;
  /** Uthmani (Hafs) text with diacritics and pause/waqf marks. */
  text: string;
  /** Present and true if this ayah contains a sajda. */
  sajda?: boolean;
}

/** One mushaf page (1..604) and everything needed to render it. */
export interface QuranPage {
  page: number;
  /** Juz (1..30) this page belongs to. */
  juz: number;
  /** Surahs appearing on this page, in order (for section headers). */
  surahIds: number[];
  ayat: Ayah[];
}

/** Chapter (surah) metadata — headings and chapter-based assignment. */
export interface Surah {
  /** 1..114. */
  id: number;
  /** Arabic name, e.g. "البقرة". */
  name: string;
  /** First Madinah page this surah appears on. */
  pageStart: number;
  /** Last Madinah page this surah appears on. */
  pageEnd: number;
  versesCount: number;
  /** Whether a Bismillah header is shown before ayah 1 (false for 1 and 9). */
  bismillahPre: boolean;
  revelation: 'meccan' | 'medinan';
}

/** Lightweight index for navigation and assignment resolution. */
export interface QuranIndex {
  totalPages: number;
  /** surahId -> [firstPage, lastPage]. */
  surahToPages: Record<number, [number, number]>;
  /** juz -> [firstPage, lastPage]. */
  juzToPages: Record<number, [number, number]>;
}
