/**
 * Service worker registration for the member app.
 *
 * Registered by hand rather than through `virtual:pwa-register` so that
 * `workbox-window` never enters the member bundle, which runs against a tight
 * size budget (`scripts/check-bundle-budgets.mjs`). The worker itself is
 * generated by `vite-plugin-pwa` — see the `VitePWA` block in `vite.config.ts`
 * for what it precaches and why the admin entry is excluded.
 *
 * The worker is a production-only concern: `npm run dev` and the test suite hit
 * a live server, and a stale precache there would only hide changes.
 */

const SERVICE_WORKER_FILE = 'sw.js';

/**
 * Register the worker once the page has loaded, so its install and precache
 * never compete with first paint for bandwidth.
 *
 * Safe to call unconditionally: it is a no-op in development, in tests, and in
 * browsers without service worker support.
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD) return;
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;

  const url = `${import.meta.env.BASE_URL}${SERVICE_WORKER_FILE}`;

  window.addEventListener('load', () => {
    // A failed registration must never take the app down with it — an
    // unregistered worker just means no offline shell.
    navigator.serviceWorker
      .register(url, { scope: import.meta.env.BASE_URL })
      .catch(() => undefined);
  });
}
